name: Build Win Portable EXE

on:
  workflow_dispatch: # Ermöglicht das manuelle Auslösen in GitHub Actions

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build applications
        run: npm run build --workspaces

      - name: Build Electron EXE
        run: npx electron-builder --win portable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SEPOffice-Portable-EXE
          path: release/*.exe
